baseURL = "https://docs.duendesoftware.com/identityserver/v5"
languageCode = "en-us"
title = "Duende IdentityServer Documentation"

theme = "hugo-theme-learn"
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
editURL = "https://github.com/DuendeSoftware/docs.duendesoftware.com/edit/main/IdentityServer/v5/docs/content/"
qs_base = "https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v5/Quickstarts"
samples_base = "https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v5"

[params.newContent]
enabled = true
url = "https://docs.duendesoftware.com/identityserver/v7/"
replace = "/v5/"
with = "/v7/"
currentVersion = "5.x"
newerVersion = "7.x"
outOfSupportSince = "December 13, 2022"