baseURL = "https://docs.duendesoftware.com/identityserver/v7"
languageCode = "en-us"
title = "Duende IdentityServer Documentation"

theme = "hugo-theme-learn"
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
editURL = "https://github.com/DuendeSoftware/docs.duendesoftware.com/edit/main/IdentityServer/v7/docs/content/"
qs_base = "https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v7/Quickstarts"
samples_base = "https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v7"

[params.baseUrls]
bff = "https://docs.duendesoftware.com/bff/v3"

[params.newContent]
enabled = false