baseURL = "https://docs.duendesoftware.com/bff/v3"
languageCode = "en-us"
title = "Duende BFF Documentation"

theme = "hugo-theme-learn"


# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
editURL = "https://github.com/DuendeSoftware/docs.duendesoftware.com/edit/main/BFF/v3/docs/content/"
samples_base = "https://github.com/DuendeSoftware/Samples/tree/main/Bff/v3"
bffBaseUrl = "https://docs.duendesoftware.com/bff/v3"

[params.PreRelease]
enabled = true

[params.newContent]
enabled = false
