baseURL = "https://docs.duendesoftware.com/identitymodel"
languageCode = "en-us"
title = "IdentityModel Documentation"

theme = "hugo-theme-learn"
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
editURL = "https://github.com/DuendeSoftware/docs.duendesoftware.com/edit/main/IdentityModel/docs/content/"