baseURL = "https://docs.duendesoftware.com/foss"
languageCode = "en-us"
title = "Duende Open Source Documentation"

theme = "hugo-theme-learn"
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
editURL = "https://github.com/DuendeSoftware/docs.duendesoftware.com/edit/main/FOSS/docs/content/"