baseURL = "https://docs.duendesoftware.com/bff/v2"
languageCode = "en-us"
title = "Duende BFF Documentation"

theme = "hugo-theme-learn"


# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
editURL = "https://github.com/DuendeSoftware/docs.duendesoftware.com/edit/main/BFF/v2/docs/content/"
samples_base = "https://github.com/DuendeSoftware/Samples/tree/main/bff/v2"

[params.newContent]
enabled = true
url = "https://docs.duendesoftware.com/bff/v3/"
replace = "/v2/"
with = "/v3/"
currentVersion = "2.x"
newerVersion = "3.x"
#outOfSupportSince = "TODO"