name: Link checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"

jobs:
  link_checker_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    name: Link Checker Job
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          
      - name: Build Astro
        run: dotnet build.cs astro-build
        
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args: '--header ''x-origin-verify: ${{ secrets.ORIGIN_VERIFICATION_HEADER_VALUE }}'' --no-progress --max-concurrency 8 --skip-missing --accept 200,429 --exclude-path server/src/Docs.Web/wwwroot/_llms-txt --exclude-path server/src/Docs.Web/wwwroot/llms.txt --exclude-path server/src/Docs.Web/wwwroot/llms-full.txt --exclude-path server/src/Docs.Web/wwwroot/llms-small.txt --exclude-loopback --require-https --exclude sample.duendesoftware.com --exclude "docs.duendesoftware.com/404" --exclude sitemap --exclude "https://github.com/DuendeArchive/IdentityModel.AspNetCore/" --root-dir "$PWD/server/src/Docs.Web/wwwroot" server/src/Docs.Web/wwwroot/**'
          fail: true
