name: Link checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 0"
  #push:
  #  branches:
  #    - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  link_checker_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    name: Link Checker Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Run build
        run: |
          echo $PWD
          ./build.sh
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args: "--no-progress --max-concurrency 8 --skip-missing --accept 200,429 --exclude-path root/_llms-txt --exclude-path root/llms.txt --exclude-path root/llms-full.txt --exclude-path root/llms-small.txt --exclude-loopback --require-https --exclude sample.duendesoftware.com --exclude docs.duendesoftware.com --exclude sitemap --exclude \"https://github.com/DuendeArchive/IdentityModel.AspNetCore/\" --root-dir \"$PWD/root\" root/**"
          fail: true
